### ISSUE TITLE
D3D Fullscreen capture

### ISSUE THREAD

**Issue by ianespana** [ra1nty/DXcam#13]
So, it was mentioned in the features that this library was able to capture screenshots of fullscreen applications, even when alt+tabbed from said applications. How would one get around to achieve this? Can't see it as an extra device, nor as an extra output, and digging around the code yielded nothing.
Some help would be greatly appreciated

**Comment by ra1nty** [comment]
Hi ianespana, thanks for trying the library out. For fullscreen applications you don't need to do anything special, just normally specify the output and device in dxcam.

The logic for alt+tab is here:
https://github.com/ra1nty/DXcam/blob/cd1c36783d206027075309d7a9be89ef5099d10a/dxcam/dxcam.py#L91-L109

Alt + Tab will yield a DXGI_ERROR_ACCESS_LOST error and the error is handled by releasing and recreating the [IDXGIOutputDuplication](https://docs.microsoft.com/en-us/windows/desktop/api/dxgi1_2/nn-dxgi1_2-idxgioutputduplication) interface.

**Comment by ianespana** [comment]
Ah, I see. So you can't exactly target a full screen application only, but it will handle the error that occurs when you alt+tab from said application

**Comment by ra1nty** [comment]
What do you mean by "target"? I imagine for capturing a full-screen application you just specify the screen that the app is on and do the capture.
