### ISSUE TITLE
Can't screenshot custom region on the screen

### ISSUE THREAD

**Issue by mitacheto** [ra1nty/DXcam#14]
region = (635, 1225, 1340, 210)
camera = dxcam.create()
frame = camera.grab()
camera.start(target_fps=60, region=region)
image = camera.get_latest_frame()

Problem: ValueError: Invalid Region: Region should be in 2560x1440

**Comment by ra1nty** [comment]
```python
region = (left, top, right, bottom)
```
Just as the error said, (635, 1225, 1340, 210) is an invalid region. top and bottom coordinates should be # of pixels from top boarder. Thus top should < bottom.
