### ISSUE TITLE
{FAQ} Automatic handling of scaled / stretched resolution.

### ISSUE THREAD

**Issue by wawan-ikhwan** [ra1nty/DXcam#16]
It said in readme.md automatic handling scaled resolution, what does it mean? Does it mean resolution like ```480p``` ```720p``` is changing dynamically or what? Can you tell me detail about it.

**Comment by ra1nty** [comment]
For example, if I play CS:GO on a 1080 p monitor using scaled full-screen, 4:3, 1280x960 stretched resolution, the output of DxCam capture will be 1280x960, in the original output quality without the scaled effect.
