### ISSUE TITLE
PyPi Release

### ISSUE THREAD

**Issue by abhiTronix** [ra1nty/DXcam#17]
Great work!

Any plans to release DXcam on pypi index too? Testpypi index cannot be used inside a python project.

**Comment by ra1nty** [comment]
Hi abhiTronix, I'm planning to release it to PyPI in early July. I'm traveling right now and do not have access to dev environments. Have a major refactor & some bug fixes in the upcoming release.

Excited to see someone submitted a proposal for vidgear. I'll ping you in the original proposal once DXcam is released on PyPI and ready for testing.

BTW I used vidgear in some of my projects and thanks for the great library!

**Comment by abhiTronix** [comment]
> Excited to see someone submitted a proposal for vidgear. I'll ping you in the original proposal once DXcam is released on PyPI and ready for testing.

@ra1nty Thanks for the heads up. DXcam looks exceptionally promising performance-wise, and I'm hoping to hear from you soon.

**Comment by ra1nty** [comment]
https://pypi.org/project/dxcam/0.0.5/ 
Hi @abhiTronix dxcam has been released to pypi.

**Comment by abhiTronix** [comment]
@ra1nty Thanks a lot, looking very promising. 👍🏽
