### ISSUE TITLE
How to get the real delay of the screenshot

### ISSUE THREAD

**Issue by Soikie** [ra1nty/DXcam#21]
run the code,you will find the last time on the pic is earier than the print time,the delay is not stable，how can i get the exact delay?
```
import dxcam
import threading
import time
import cv2

global A 
A = True

def pr():
    while True:
        if A == False:
            break
        print(time.time())

scr = dxcam.create()

p1 = threading.Thread(target=pr)
p1.start()

time.sleep(2)


t0 = time.time()
pic = scr.grab()

t1 = time.time()

A = False
time.sleep(0.3)
print('start_time:{},end_time:{},time gap: {}'.format(t0,t1,t1 -t0))

cv2.imwrite('speed.jpg',pic)
```

**Comment by ra1nty** [comment]
python's ```time.time()``` cant give you accurate measure. Try to use ```time.perf_counter()```. But still, the minimum resolution is ~16ms on windows and not suitable for the task.

**Comment by crackwitz** [comment]
15.625 Ms, due to how the system scheduler allocates time to threads/processes.

`time.perf_counter()` *is* more accurate than that however.
