### ISSUE TITLE
setting region causes issue when color is set to GRAY

### ISSUE THREAD

**Issue by DaPlatapus** [ra1nty/DXcam#25]
Using the following code

    camera = dxcam.create(output_idx=0, output_color="GRAY")
    frame = camera.grab(region=region)

creates this error

    File ~\anaconda3\lib\site-packages\dxcam\processor\numpy_processor.py:54, in NumpyProcessor.process(self, rect, width, height, 
    region, rotation_angle)
         51     image = image[:height, :, :]
         53 if region[2] - region[0] != width or region[3] - region[1] != height:
    ---> 54     image = image[region[1] : region[3], region[0] : region[2], :]
         56 return image
    IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

This is because when using "GRAY" option, the output image is only in 2 dimension not 3. I was able to fix the issue by changing line 54 into the following try block.

            try:
                image = image[region[1] : region[3], region[0] : region[2], :]
            except:
                image = image[region[1] : region[3], region[0] : region[2]]

While this solves the issue, I think it would be faster if an 'if color_mode == "GRAY" ' statement is used instead of try/except block. However, I am very new to python/coding and am unsure how to pass color_mode argument into def process().
If anyone could teach me how to do that, I would appreciate it.

**Comment by crackwitz** [comment]
Use this:
```python
(x0, y0, x1, y1) = region
image = image[y0:y1, x0:x1, ...]
```

**Comment by DaPlatapus** [comment]
Thanks!

**Comment by ra1nty** [comment]
Closing -- will be fixed in upcoming release
