### ISSUE TITLE
Region should be in 1920x1080

### ISSUE THREAD

**Issue by ninjatall12** [ra1nty/DXcam#26]
I'm getting a bug where if the values of top and left are not 0 i get outputted region should be in 1920x1080
[code.txt](https://github.com/ra1nty/DXcam/files/9208278/code.txt)
![image](https://user-images.githubusercontent.com/58861295/181485667-70ff2bba-6b39-4e95-9c88-83e1417c1fe3.png)

**Comment by ra1nty** [comment]
```python
left, top = (1920 - 640) // 2, (1080 - 640) // 2
right, bottom = left + 640, top + 640
region = (left, top, right, bottom)
```
^ See doc.
