### ISSUE TITLE
Need help with numpy and dxcam

### ISSUE THREAD

**Issue by ninjatall12** [ra1nty/DXcam#27]
![image](https://user-images.githubusercontent.com/58861295/181591331-ad04a616-dce3-44c5-821e-98228021e311.png)
![image](https://user-images.githubusercontent.com/58861295/181591396-3dd3f237-3727-47cc-8c5f-6610608bc9f7.png)

**Comment by crackwitz** [comment]
You must ask those questions in an appropriate forum. This here is for *bug reports* in *this library*. Do not ask such questions here.

Try one of these: https://www.python.org/community/forums/

**Comment by ra1nty** [comment]
> You must ask those questions in an appropriate forum. This here is for _bug reports_ in _this library_. Do not ask such questions here.
> 
> Try one of these: https://www.python.org/community/forums/
^
Thanks Chris!
