### ISSUE TITLE
Incompatibility using with opencv?

### ISSUE THREAD

**Issue by abdudsoul** [ra1nty/DXcam#32]
While setting screenshot image output to RGB:
`cap = dxcam.create(output_idx=0, output_color="RGB")`
and using opencv, I am getting error:
` Given groups=1, weight of size [32, 3, 3, 3], expected input[1, 384, 640, 3] to have 3 channels, but got 384 channels instead`

I am able to use BGR and convert from BGR to RGB using:
`img = img[:, :, ::-1].transpose(2, 0, 1)`

but switching from mss I have already saved 10ms using DXCam and without having to convert from BGR to RGB would help save alot.

**Comment by crackwitz** [comment]
Not a dxcam issue. You don't know about NCHW vs NHWC
