### ISSUE TITLE
To screenshot a specific region, the FPS is lower than MSS, and the screenshot frame rate is also very low when playing large games

### ISSUE THREAD

**Issue by Strive1s** [ra1nty/DXcam#36]
![} )Q4Y MVUH%~{W8COG_OC](https://user-images.githubusercontent.com/85618861/194747878-b718ec4c-ecba-4bec-9bb5-5d5c49cd6fe2.png)
I would like to know how to optimize small region screenshots, this is very helpful for me

**Comment by Strive1s** [comment]
PC (5600X + 2070S)

**Comment by ra1nty** [comment]
You need to have something constantly rendering to your capture region to do the comparison. E.g. have https://www.testufo.com/ open and benchmarking screenshoting the middle of the screen. If nothing is constantly rendered then mss will just return the last frame, hence the inaccurate result.

**Comment by Strive1s** [comment]
But I'm trying to render screenshots fast in game (CS), but FPS is still low, lower than MSS
