### ISSUE TITLE
Any idea how can I send a frame over by a string?

### ISSUE THREAD

**Issue by Godwhitelight** [ra1nty/DXcam#39]
I want to send a frame by text so I could send it over the network

Any ideas for how I could make this a shere screen would be nicely accepted

**Comment by ra1nty** [comment]
This question is too generic: the captured frame is a NumPy ndarray and you can do whatever you want with it. A good starting point will probably be reading through https://docs.python.org/3/library/socket.html and understanding the basic concepts.
