### ISSUE TITLE
Make `opencv-python` dependency optional

### ISSUE THREAD

**Issue by abhiTronix** [ra1nty/DXcam#45]
Hi @ra1nty, I'm working on integrating this library finally. 🍻 

But I found that hardcoding `opencv-python` as dependency is  a very bad idea, since there are several ways to install `opencv` such as from PyPi, APT, compile form source etc. And moreover there are several version of same binary such as `opencv-python-headless`, `opencv-contrib-python` etc. on pypi itself. So having multiple version of same library on your system will definitely break it, since installing `opencv-python` won't check existence of other OpenCV libs.

## Possible Solution
Make `opencv-python` optional by moving it from `install_requires` to `extras_require` and provide it under naming such as `cv2` such that people can install it using `pip install dxcam[cv2]` command when they know they don't already have OpenCV libs already installed.

**Note:** Make sure `cv2` is not imported globally but withing a class (or more appropriately its method), so that it won't throw error directly when importing `dxcam` but only when specific class or functionality is imported.

**Comment by abhiTronix** [comment]
Related issue #43

**Comment by abhiTronix** [comment]
@ra1nty If you say, I can prepare a PR for the same. 😃

**Comment by abhiTronix** [comment]
@ra1nty Done!!!

**Comment by ra1nty** [comment]
Hi @abhiTronix , thanks for the contribution! Yes it is indeed a good idea to make opencv optional. I've merged #46 and will release it shortly. Cheers 🍻
