### ISSUE TITLE
[help] How crop the result of camera.get_latest_frame()

### ISSUE THREAD

**Issue by skhrlx** [ra1nty/DXcam#63]
hi, currently i need record a region, but, i need two different parts of this `region`, the main question here is how i can crop the image using a new `region`

ex, for my first one, i need to get this entire region: 
```
left, top = (1920 - 640) // 2, (1080 - 640) // 2
right, bottom = left + 640, top + 640
region = (left, top, right, bottom)
```

but later, i need this region:
```
left, top = (1024 - 640) // 2, (768- 640) // 2
right, bottom = left + 640, top + 640
region = (left, top, right, bottom)
```

>just for example the values<

Currently im using numpy and cv2 on my project too

**Comment by traavnik** [comment]
A simple .stop() before new .start() with a new region doesn't work? Or just a .grab() with specified region if you're after a single screenshot.

Alternatively, you could always capture the whole screen and simply slice the numpy array to your liking. This would be the go to method if you're after two regions from the same frame. Not sure if this was what you were after?

**Comment by skhrlx** [comment]
> A simple .stop() before new .start() with a new region doesn't work? Or just a .grab() with specified region if you're after a single screenshot.
> 
> Alternatively, you could always capture the whole screen and simply slice the numpy array to your liking. This would be the go to method if you're after two regions from the same frame. Not sure if this was what you were after?

I ve done that after some two days after I post it, currently I'm slicing the numpy array after grab a larger area
