### ISSUE TITLE
So are you unable to just update dxcam to perform like dxshot?

### ISSUE THREAD

**Issue by iminsideyou** [ra1nty/DXcam#65]
obv this is so buggy it's not reliable to use so you keep posting to that dxshot thing. Why not just update dxcam so it works. Pretty pathetic ngl. literally mss is better.

**Comment by iminsideyou** [comment]
import dxshot
ModuleNotFoundError: No module named 'dxshot'
shocker.

**Comment by ra1nty** [comment]
dxshot seems to be a separately maintained compiled version of dxcam so why don’t u try to read and ask the right personnel
